@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Sep 23 00:23:35 +0545 2024
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim four_bitaddsub_behav -key {Behavioral:sim_1:Functional:four_bitaddsub} -tclbatch four_bitaddsub.tcl -view C:/Users/Asus/Desktop/Vivado/four_bitaddsub_dupli/four_bit_add_sub/four_bitaddsub_behav.wcfg -log simulate.log"
call xsim  four_bitaddsub_behav -key {Behavioral:sim_1:Functional:four_bitaddsub} -tclbatch four_bitaddsub.tcl -view C:/Users/Asus/Desktop/Vivado/four_bitaddsub_dupli/four_bit_add_sub/four_bitaddsub_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
